/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.ongakucraft.app

import com.ongakucraft.app.data.ArticDataApp
import spock.lang.Specification

class ArticDataAppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new ArticDataApp()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
